name: game_collection
description: "SnapPlay - 30+ Offline Mini Games Collection: Ludo, Chess, Carrom & more."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Game Engine
  flame: ^1.18.0
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # State Management
  provider: ^6.1.2
  
  # Haptic Feedback & Vibration
  vibration: ^2.0.0
  
  # Audio (for sound effects)
  audioplayers: ^6.0.0

  # Utils
  intl: ^0.19.0
  lottie: ^3.3.2
  flutter_staggered_grid_view: ^0.7.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk value

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/icons/
    - assets/images/carrom/
    - assets/logo.png
